/**:
  ros__parameters:
    min_longitudinal_offset: 2.85
    max_longitudinal_offset: 2.95
    min_lateral_offset: 0.56
    max_lateral_offset: 0.65
    min_height_offset: 0.125
    max_height_offset: 0.142
